### ISSUE TITLE
Throw Exceptions for invalid input

### ISSUE THREAD

**Issue by ansstuff** [XMunkki/FixPointCS#7]
Currently, providing an invalid input to functions like Sqrt(<0) simply returns 0, which hides the problem and leads to debugging hell.

Returning a corrent result (NaN, #6 ) instead of zero would be slightly better - NaN usually breaks everything it touches and then you can trace back to when the result first became NaN.
While zero is incredibly common value, and is often a technically valid result, except not being logically valid in the context. Usually zero doesn't produce any noticeable bugs until after release.

So, in Debug mode (when DEBUG is defined) and arguably in Release mode as well (maybe provide an optional define like STRICT_VALIDATIONS) there should be exceptions thrown everywhere necessary, in order to catch bugs early. Any invalid input should be highlighted, not concealed.

**Comment by petrikero** [comment]
I agree in principle that errors should not be concealed, but made as noisy as possible. There are some conflicting design principles in this case, though.

The library actually used to have some detection for invalid inputs, but we ultimately decided to go with the silent handling and returning zeros. The main reasons for not doing the checks is that there are multiple ways of handling them, depending on the language as well. Especially many C++ don't want to use exceptions in such low level code. Determinism across languages is a key feature of the library, which I'm not willing to compromise on without really strong reasons.

As mentioned in the other issue, I don't really see NaNs and infinities being viable due to the performance impact they would have. Simple operations like addition would become many times slower from the inf/NaN checks.

My recommendation would be to include the checks in the scalar/vector structs, where each project can make their own decisions on how they want to handle any errors. It sounds like a good idea to include them in the provided example math library, but I'm not sure when I have the time to implement them.

**Comment by ansstuff** [comment]
Yeah, I was mentioning NaNs as only a half-solution. Throwing exceptions is better way, and also a non-taxing one.
I don't see the conflict if the exception is optional and zero is returned otherwise.

```
#if DEBUG
#define THROW_EXCEPTIONS
#endif

public static long Sqrt(long x)
        {
            // Return 0 for all negative values.
            if (x < 0)
            {
#if THROW_EXCEPTIONS
                  FP_EXCEPTION();    // customized per-language
#endif
                  return 0;
            }
```

Checking the input in scalar struct a less desirable option, because then there would be double-checks (both in F64 and Fixed64), while the aforementioned style doesn't affect performance at all.
And I think such low-level checks should be covered by core instead of user, because they directly depend on the core implementation. Take for example `Pow(long x, long exponent)`. Currently it cannot handle negative x, which is counterintuitive since Math.Pow() handles negative base well if the exponent is an integer number. Even if user implements external checking, future core implementation could change (perhaps include the integer exponent case someday!), thus changing the input requirements and making user's own checks obsolete.

**Comment by ansstuff** [comment]
By the way, I've noticed probably a typo in Fixed32/Fixed64:
```
        public static long SqrtPrecise(long a)
        {
            // Adapted from https://github.com/chmike/fpsqrt
            if (a < 0)
                  return -1;
```
It returns -1 instead of zero.

**Comment by petrikero** [comment]
That's actually a really good idea! I'll run it thru with the other author to make sure it doesn't conflict with the transpiler to C++/Java. The transpiler is a fairly stupid regex-style preprocessor, so it may need finesse to get working with the preprocessor usage for exceptions.

Thanks for pointing out the -1 instead of 0. Maybe the -1 could be justified, as kinda NaNish behavior, but I changed it to 0 to be more consistent with other functions.

**Comment by ansstuff** [comment]
I thought about whether -1 would be a better fallback than 0.
But it isn't NANish enough to facilitate reliable propagation of error signal. And at the same time, it isn't neutral enough to minimize consequences of invalid input.
Zero is probably the best bet when trying to sweep things under the rug. I guess, it might save the day when the invalid input is caused by a rare heisenbug.
But anyway, a probabilistic fallback only becomes an acceptable policy if vast majority of bugs were actually fixed (not swept) before release, that's why the library seriously needs a way to signal errors.

**Comment by petrikero** [comment]
This is now finally implemented. The default behavior is still no exceptions (due to backwards compatibility and to keep the C++ implementation clean), but you can now define your own invalid argument handlers in C# and C++. Java version doesn't yet support this.

**Comment by ansstuff** [comment]
Thank you. Your implementation is more clean than my spamming with preprocessor directives. But are you positive there's zero overhead when InvalidArgument() is empty?
CPP compilers surely are smart enough to remove the redundant condition check (when inlined function is empty) such as:
```
            if (a <= 0)
            {
                if (a < 0)
                    FixedUtil.InvalidArgument("Fixed64.SqrtPrecise", "a", a);
                return 0;
            }
```
Dunno if the same can be assumed with JIT compilers. Generated IL code looks rather involved, at least.
My idea was to surround all those calls with ifdefs like that:
```
            if (a <= 0)
            {
#if FP_CUSTOM_INVALID_ARGS
                if (a < 0)
                    FixedUtil.InvalidArgument("Fixed64.SqrtPrecise", "a", a);
#endif
                return 0;
            }
```
Do you think it's unnecessary?

**Comment by ansstuff** [comment]
Also, now that there's this customizable debugging instrumentation, it's probably time to change occasional Asserts to InvalidArgument() calls

``` 
        private static int Atan2Div(long y, long x)
        {
            Debug.Assert(y >= 0 && x > 0 && x >= y);
```

Even if some of later Asserts don't look like they are directly caused by invalid input, they actually are, because what else.

Majority of those Asserts should even return 0 as well.

**Comment by petrikero** [comment]
There is indeed some minimal overhead in the C# implementation. The added overhead is typically in places which should rarely be visited, or when an error is about to occur anyway. I should have probably made more measurements to make sure it's not affecting performance in realistic use cases, but unfortunately my time on this project is fairly limited. If you notice any non-trivial performance degradations, the C# #ifdef solution is also possible. The current transpiler might need some fixing, though, so there's some hidden overhead to it.

The Debug.Assert()s are for internal consistency checks and should never get triggered. If you can get any of them to trigger via the public API, please do file it as a bug report about it separately.
